### ISSUE TITLE
Validation to eject members

### ISSUE THREAD

**Issue by fbrahman** [bcmiller713/devcircle#77]
Currently, all viewers can eject members. This needs to be restricted to the owner/creator only. 

Conditional formatting to be updated to only show 'x' and eject options for the correct role (owner/creator). 

Secondary check when request sent to verify role again prior to database changes taking effect.

**Comment by aarongaither** [comment]
Agreed, i think the secondary check should also be implemented for all other user role defined actions.
Also, we could take it one step further and send the user id to the server, then cross ref the id vs what the db believes the roles auth level is, before performing and data mutation.
