### ISSUE TITLE
general cohort chat

### ISSUE THREAD

**Issue by aarongaither** [bcmiller713/devcircle#80]
In order to enforce the community aspect it would beneficial to at least have a large single threaded general chat.

**Comment by aarongaither** [comment]
Any thoughts on this one? Once I get the other websocket bug squashed, this would be trivial. Question may be, what page does it go on and where to put it?

**Comment by fbrahman** [comment]
Two possibilities are the explore page and dashboard page. 
Would it bring greater value to have a general chat? 
Most may use more robust chat applications like slack instead for general chatting.

**Comment by aarongaither** [comment]
Closing this issue for now. We can re-open it if we ever determine this adds value, at a later date.
